canonical/terraform-provider-maas

- examples/machines.tf
- go.mod
- go.sum
- maas/provider.go
- maas/resource_maas_block_device.go
Add `maas_block_device` Terraform managed resource, and updated examples with usage information.
It allows configuration of new / existing block devices from MAAS machines.
> Add maas_block_device managed resource

- go.mod
- go.sum
Fixes https://github.com/maas/terraform-provider-maas/issues/13 and points the gomaasclient module at the repo under the MAAS org.
> bump gomaasclient version

- .github/workflows/release.yml
- .github/workflows/test.yml
This is a small PR to introduce the test and release GitHub action workflows.  These have been raised from the Terraform provider scaffolding repo.  The aim is to be a starting point that can be expanded.
The `release.yml` representing the release workflow will require additional environment variables to be setup in the repo and this can be expanded later.
The `test.yml` representing the test workflow will allow us to introduce the acceptance tests.  The idea is to have a basic acceptance test that covers the provider.go and the error handling around the environment variables.
> Introduce GitHub workflows

- README.md
> docs: fix min go version in README

- go.mod
- go.sum
This PR includes changes to gomaasclient, implemented on https://github.com/maas/gomaasclient/pull/14
> Bump gomaasclient/gomaasapi to latest version

- README.md
- go.mod
In order to use recent version of Terraform plugin SDK [0] we need to bump our minimal Go version to 1.20 because of this PR [1] being merged.
Also each major Go release is supported until there are two newer major releases [2].
[0]: github.com/hashicorp/terraform-plugin-sdk/v2
[1]: https://github.com/maas/terraform-provider-maas/pull/83
[2]: https://go.dev/doc/devel/release#policy
> all: update Go module to Go 1.20

- Makefile
```
❯ gofmt --help
usage: gofmt [flags] [path ...]
-cpuprofile string
write cpu profile to this file
-d    display diffs instead of rewriting files
-e    report all errors (not just the first 10 on different lines)
-l    list files whose formatting differs from gofmt's
-r string
rewrite rule (e.g., 'a[b:len(a)] -> a[b:]')
-s    simplify code
-w    write result to (source) file instead of stdout
```
> ci: fix gofmt params, so it scans all files

- .github/workflows/test.yml
- README.md
1.4 is also EOL, however it is still widely used.
https://support.hashicorp.com/hc/en-us/articles/360021185113
> all: drop support of Terraform EOL versions

- .github/workflows/delabeler.yml
Introduce label based workflow.
MAAS maintainers have to apply special label in order to trigger integration tests using real MAAS installation.
Labels are automatically removed when new commits are pushed to the PR branch.
- `Review: Core +1` label triggers execution of end-to-end tests
> ci: special labels to trigger integration tests

- maas/resource_maas_instance.go
Apply `ForceNew` to internal fields of `allocate_params`, `deploy_params`, `network_interfaces`.
Since a change on any of these fields indicates the intention to release the machine and deploy again, this has to be reflected in Terraform. In addition, without setting the `ForceNew` option, Terraform is not aware that has to perform release and deploy aka destroy and create. Instead, it will try to update in place the fields leading to a Terraform error since there is no update action for `maas_instance` resource.
Resolves #45
> Fix `maas_instance` updates

- docs/resources/instance.md
- maas/resource_maas_instance.go
Add system_id as an optional allocate parameter. If provided, the maas_instance will try to deploy a machine with the given `system_id`.
Resolves: #113
> Deploy a machine based on its `system_id`

- docs/resources/vm_host.md
- maas/resource_maas_instance.go
- maas/resource_maas_vm_host.go
VM Host operations can take longer than the alloted 20 minutes, this should introduce a user configurable `timeouts` block to increase that time if needed.
> feat: add configurable create timeout for VM hosts

- docs/resources/network_interface_physical.md
- examples/resources/maas_network_interface_physical/import.sh
- maas/resource_maas_network_interface_physical.go
- maas/resource_maas_network_interface_physical_test.go
This PR includes the following changes:
- Change the delimiter of importing physical interfaces from `:` to `/`
- Allow import by MAC Address as advertised
- Do not break idempotency when importing existing resources
- Add acceptance tests for physical interfaces
Fixes: #163
> fix: properly import physical interfaces

- docs/resources/machine.md
- maas/resource_maas_machine.go
- maas/resource_maas_network_interface_physical.go
This PR includes the following changes:
- add `network_interfaces` calculated field on `maas_machine`. The field includes a set of MAC addresses of discovered interfaces during commissioning.
- change logic of `maas_network_interface_physical` when another interface is found with the same MAC address  during creation. From now on, an update operation is tried instead of no op.
- improve the logic of create, update actions. Since MAAS API is returning the created/updated object there is no need to call read action before returning. By using this improvement, we avoid running the expensive operations of `client.Machines.Get` and `client.NetworkInterface.Get`.
- make `vlan` field of `maas_network_interface_physical` "computable". Interfaces detected during commissioning already belong to a …
> fix: manage existing physical interfaces from commissioning

- .github/workflows/release.yml
Based on goreleaser [deprecations](https://goreleaser.com/deprecations/#__tabbed_17_1), `--rm-dist` is replaced by `--clean`.
> ci: fix goreleaser

- maas/resource_maas_network_interface_bond_test.go
- maas/resource_maas_network_interface_bridge_test.go
- maas/resource_maas_network_interface_physical_test.go
- maas/resource_maas_network_interface_vlan.go
- maas/resource_maas_network_interface_vlan_test.go
- Parse `vlan` field as integer rather than string
- Add acceptance test to check the context update of all interface types
Resolves GH: #206
> fix: correctly parse vlan field of VLAN interfaces

- README.md
- go.mod
Each major Go release is supported until there are two newer major releases [link].
[link]: https://go.dev/doc/devel/release#policy
> chore: update Go module to Go 1.22

- docs/resources/network_interface_vlan.md
- maas/resource_maas_network_interface_link.go
- maas/resource_maas_network_interface_link_test.go
- maas/resource_maas_network_interface_vlan.go
- maas/resource_maas_network_interface_vlan_test.go
- Unlink all existing links of an interface before create a new link, instead of disconnect
- Add a new attribute to vlan interface to set a name or calculate it from MAAS
- Add acceptance tests for `maas_interface_link`
- Make `vlan` field of a vlan interface a mandatory field with force re-creation, since it was accidentally marked as optional
Resolves: #259
> fix: properly unlink existing links before creating a link

- DEVELOPMENT.md
- maas/data_source_maas_device_test.go
- maas/resource_maas_device_test.go
- maas/resource_maas_network_interface_bond_test.go
- maas/resource_maas_network_interface_bridge_test.go
- maas/resource_maas_network_interface_link_test.go
- maas/resource_maas_network_interface_physical_test.go
- maas/resource_maas_network_interface_vlan_test.go
- maas/testutils/helpers.go
Stop using the same MAC address for interface creation during acceptance tests. If `maas_interface_bridge` and `maas_interface_link` tests run on parallel against the same machine, using the same MAC address for creating interfaces can cause issues. Being more specific, the two tests can compete for the same interface and the delete part of the one can delete the interface of the other.
Changes include:
- Stop expecting a pre-created fabric for the test. Instead create different fabrics per interface acceptance test
- Introduce a random MAC address generator to produce random MAC addresses for the needs of the tests
- Remove references to `TF_ACC_FABRIC` since it is not needed anymore
N/A
> fix: use unique MAC addresses for tf acc interfaces

- maas/resource_maas_device_test.go
- maas/resource_maas_network_interface_link_test.go
- maas/resource_maas_subnet_ip_range_test.go
- maas/testutils/helpers.go
- maas/testutils/helpers_test.go
Add generating a random CIDR test function, to highly reduce the likelyhood of CIDR collisions during test which were the cause of some flakey tests.
CI run with CIDR error: http://maas-ci.internal:8080/view/terraform/job/gh-maas-terraform-provider-tester/419/console
> fix: avoid subnet cidr collisions

- go.mod
- go.sum
Bumps gomaasclient version from 0.8.0 -> 0.9.0 to use the VLAN DHCP setter update.
NA.
> chore(deps): bump github.com/canonical/gomaasclient from 0.8.0 to 0.9.0

- docs/resources/instance.md
- maas/resource_maas_instance.go
- maas/resource_maas_instance_test.go
Add ability to erase disks when destroying the resource `maas_instance`. 
Resolves: #72 
Resolves: #260
> feat: 72-erase-disks-when-destroying-instances
